

var restaurantData = {
	b: "Welcome to Fat Frank's Fish and Chips! Would you like a table?",
		b1: "Yes, I'd like a table for 2 please.",
			b1b: "Great, please come this way.<br>Would you like some drinks?",
				b1b1: "Yes please. We would like a bottle of red wine.",
					b1b1b: "Of course. Would you like to see the wine menu?",
						b1b1b1: "No thank you. We will just have the 'house' red.",
							b1b1b1b: "Very well. Let me just go and get you some glasses.",
						b1b1b2: "Yes please.",
							b1b1b2b: "OK - I will just bring you the menu.",
						b1b1b3: "No thank you. Just bring us a wine you recommend.",
							b1b1b3b: "I can recommend the Chardonnay, I'll go and fetch a bottle.",
				b1b2: "Yes please. Could we see the menu?",
					b1b2b: "Certainly, here you go. What can I get you?",
						b1b2b1: "Can we have two cans of Coke please.",
							b1b2b1b: "Of course, two Cokes. I'll also bring you a food menu.",
						b1b2b2: "We will have a glass of orange juice and a bottle of beer please.",
							b1b2b2b: "An orange juice and a beer. I'll bring those now, and also a food menu.",
						b1b2b3: "A bottle of white wine, please.",
							b1b2b3b: "Good choice - the house wine is lovely.",
				b1b3: "No thank you. We'll just be having food.",
					b1b3b: "OK. Here is the food menu.",
						b1b3b1: "Thank you. We will have fish and chips please.",
							b1b3b1b: "Two plates of fish and chips - good choice.",
						b1b3b2: "Thank you. We'd like tuna salad and a bowl of chips please.",
							b1b3b2b: "I'm afraid we are out of chips. I will bring you some potatoes instead.",
						b1b3b3: "Thank you. I would like a tuna pizza please.",
							b1b3b3b: "A personal favourite. Coming right up.",
		b2: "No, can I make a reservation for later?",
			b2b: "Of course. What time would like to reserve a table for?",
				b2b1: "Half past eight this evening, please.",
					b2b1b: "That is fine. Would you like a table near the jazz band?",
						b2b1b1: "Yes please.",
							b2b1b1b: "I'll try and get you a table right at the front.",
						b2b1b2: "No thank you.",
							b2b1b2b: "OK, we have a nice table near to the window, which I'll reserve.",
						b2b1b3: "I don't mind.",
							b2b1b3b: "Very well then. See you later!",
				b2b2: "What time are you open until?",
					b2b2b: "We are open until 10pm tonight.",
						b2b2b1: "OK - please can we book a table at 9pm.",
							b2b2b1b: "Yes sure, a table at 9pm.",
						b2b2b2: "Great, can I book a table for 4 people at 8 o'clock please?",
							b2b2b2b: "Certainly. A table for 4, at 8 o'clock.",
						b2b2b3: "Sorry, actually, that's too early for me.",
							b2b2b3b: "I'm sorry to hear that. Maybe another day then.",
				b2b3: "I would like to reserve a table for tomorrow lunch.",
					b2b3b: "OK - how many people will be eating?",
						b2b3b1: "Just me, thank you.",
							b2b3b1b: "Very well. A table for one, tomorrow at lunch.",
						b2b3b2: "It will be myself and my brother.",
							b2b3b2b: "Good, a table for two at lunchtime tomorrow.",
						b2b3b3: "We'll have a table for four people please.",
							b2b3b3b: "Let me just check... yes, that's fine. See you tomorrow.",
		b3: "",
			b3b: "OK, here is the take-away menu.",
				b3b1: "I'll have a burger and a beer please.",
					b3b1b: "I'm afraid we're out of beers - can I get you anything else instead?",
						b3b1b1: "I'll have a Coke instead.",
							b3b1b1b: "Fantastic choice. I'll bring you your burger and Coke shortly.",
						b3b1b2: "Do you have any other alcoholic drinks?",
							b3b1b2b: "We do have shots. I'll bring you a shot with your burger.",
						b3b1b3: "No thanks - I'm off.",
							b3b1b3b: "Oh, OK. Come back again soon - we normally have a good range of beer. Stella and Fosters mainly.",
				b3b2: "This menu looks awful! Do you have anything nicer?",
					b3b2b: "I'm afraid this is all we have, sir.",
						b3b2b1: "OK - I'll get one small 'Fish Surprise' please.",
							b3b2b1b: "Coming right up. It really is quite a surprising dish.",
						b3b2b2: "Sorry - I am leaving.",
							b3b2b2b: "Suit yourself. Come back again soon!",
						b3b2b3: "I'll just have a water please.",
							b3b2b3b: "I'm afraid we're having problems with our drainage, so that won't be possible, sir.",
				b3b3: "Can you recommend anything?",
					b3b3b: "The eels are very tasty, and the soup goes well with them.",
						b3b3b1: "Great, I'll get the eels and the soup then please.",
							b3b3b1b: "A good choice - eels with leek soup to take away.",
						b3b3b2: "I don't like eels - what else do you have?",
							b3b3b2b: "We have a wide variety of tuna products.",
						b3b3b3: "I think I'll get the soup and a tuna pizza please.",
							b3b3b3b: "Excellent choice - the tuna pizza is a personal favourite.",

}


var restaurantDataTranslated = {
	b: "Bienvenido a Fish and Chips Fat Frank! &iquest;Te gustar&iacute;a una mesa?",
		b1: "S&iacute;, me gustar&iacute;a una mesa para 2 por favor.",
			b1b: "Grande, por favor, ven de esta manera. <br> &iquest;Quieres algunas bebidas?",
				b1b1: "S&iacute;, por favor. Nos gustar&iacute;a una botella de vino tinto.",
					b1b1b: "Por supuesto. &iquest;Te gustar&iacute;a ver la carta de vinos?",
						b1b1b1: "No gracias. No hacemos m&aacute;s que tener la roja 'casa'.",
							b1b1b1b: "Muy bien. D&eacute;jame ir y te dan unas gafas.",
						b1b1b2: "S&iacute;, por favor.",
							b1b1b2b: "OK - Sólo te traigo el men&uacute;.",
						b1b1b3: "No gracias. Sólo tiene que traer un vino recomiendas.",
							b1b1b3b: "Puedo recomendar el Chardonnay, yo ir&eacute; a buscar una botella.",
				b1b2: "S&iacute;, por favor. &iquest;Podr&iacute;amos ver el men&uacute;?",
					b1b2b: "Ciertamente, aqu&iacute; tienes. &iquest;Qu&eacute; puedo hacer por ti?",
						b1b2b1: "Can we have two cans of Coke please.",
							b1b2b1b: "Of course, two Cokes. I'll also bring you a food menu.",
						b1b2b2: "We will have a glass of orange juice and a bottle of beer please.",
							b1b2b2b: "An orange juice and a beer. I'll bring those now, and also a food menu.",
						b1b2b3: "A bottle of white wine, please.",
							b1b2b3b: "Good choice - the house wine is lovely.",
				b1b3: "No gracias. Tendremos celebraremos alimentos.",
					b1b3b: "OK. Here is the food menu.",
						b1b3b1: "Thank you. We will have fish and chips please.",
							b1b3b1b: "Two plates of fish and chips - good choice.",
						b1b3b2: "Thank you. We'd like tuna salad and a bowl of chips please.",
							b1b3b2b: "I'm afraid we are out of chips. I will bring you some potatoes instead.",
						b1b3b3: "Thank you. I would like a tuna pizza please.",
							b1b3b3b: "A personal favourite. Coming right up.",
		b2: "No, puedo hacer una reserva para m&aacute;s tarde?",
			b2b: "Por supuesto. &iquest;A qu&eacute; hora le gustar&iacute;a reservar una mesa para?",
				b2b1: "Las ocho y media de esta tarde, por favor.",
					b2b1b: "That is fine. Would you like a table near the jazz band?",
						b2b1b1: "Yes please.",
							b2b1b1b: "I'll try and get you a table right at the front.",
						b2b1b2: "No thank you.",
							b2b1b2b: "OK, we have a nice table near to the window, which I'll reserve.",
						b2b1b3: "I don't mind.",
							b2b1b3b: "Very well then. See you later!",
				b2b2: "&iquest;A qu&eacute; hora se abre hasta que?",
					b2b2b: "Estamos abiertos hasta las 10 pm esta noche.",
						b2b2b1: "OK - please can we book a table at 9pm.",
							b2b2b1b: "Yes sure, a table at 9pm.",
						b2b2b2: "Great, can I book a table for 4 people at 8 o'clock please?",
							b2b2b2b: "Certainly. A table for 4, at 8 o'clock.",
						b2b2b3: "Sorry, actually, that's too early for me.",
							b2b2b3b: "I'm sorry to hear that. Maybe another day then.",
				b2b3: "Me gustar&iacute;a reservar una mesa para el almuerzo de mañana.",
					b2b3b: "OK - &iquest;cu&aacute;ntas personas ser&aacute;n comiendo?",
						b2b3b1: "Just me, thank you.",
							b2b3b1b: "Very well. A table for one, tomorrow at lunch.",
						b2b3b2: "It will be myself and my brother.",
							b2b3b2b: "Good, a table for two at lunchtime tomorrow.",
						b2b3b3: "We'll have a table for four people please.",
							b2b3b3b: "Let me just check... yes, that's fine. See you tomorrow.",
		b3: "No, me gustar&iacute;a pedir comida para llevar por favor.",
			b3b: "Bien, aqu&iacute; est&aacute; el men&uacute; para llevar.",
				b3b1: "Voy a tener una hamburguesa y una cerveza por favor.",
					b3b1b: "Me temo que estamos fuera de cervezas - te pongo otra cosa en su lugar?",
						b3b1b1: "I'll have a Coke instead.",
							b3b1b1b: "Fantastic choice. I'll bring you your burger and Coke shortly.",
						b3b1b2: "Do you have any other alcoholic drinks?",
							b3b1b2b: "We do have shots. I'll bring you a shot with your burger.",
						b3b1b3: "No thanks - I'm off.",
							b3b1b3b: "Oh, OK. Come back again soon - we normally have a good range of beer. Stella and Fosters mainly.",
				b3b2: "Este men&uacute; se ve horrible! &iquest;Tienes algo m&aacute;s bonito?",
					b3b2b: "Me temo que esto es todo lo que tenemos, señor.",
						b3b2b1: "OK - I'll get one small 'Fish Surprise' please.",
							b3b2b1b: "Coming right up. It really is quite a surprising dish.",
						b3b2b2: "Sorry - I am leaving.",
							b3b2b2b: "Suit yourself. Come back again soon!",
						b3b2b3: "I'll just have a water please.",
							b3b2b3b: "I'm afraid we're having problems with our drainage, so that won't be possible, sir.",
				b3b3: "&iquest;Me puede recomendar algo?",
					b3b3b: "Las anguilas son muy sabrosos, y la sopa va bien con ellos.",
						b3b3b1: "Great, I'll get the eels and the soup then please.",
							b3b3b1b: "A good choice - eels with leek soup to take away.",
						b3b3b2: "I don't like eels - what else do you have?",
							b3b3b2b: "We have a wide variety of tuna products.",
						b3b3b3: "I think I'll get the soup and a tuna pizza please.",
							b3b3b3b: "Excellent choice - the tuna pizza is a personal favourite.",

}


var stationDataEnglish = {b:"Welcome to King's Cross train station. How can I help you?",b1:"Can I buy one ticket to Liverpool please.",b1b:"Would you like a First or Standard class ticket?",b1b1:"First class, please.",b1b1b:"One way or return?",b1b1b1:"A one way ticket, please.",b1b1b1b:"That will be £24 please.",x:"x",x:"x",x:"x",x:"x",x:"x",b1b1b2:"A return ticket, please.",b1b1b2b:"That will be £40 please.",x:"x",x:"x",x:"x",x:"x",x:"x",b1b1b3:"",b1b1b3b:"",x:"x",x:"x",x:"x",b1b2:"Standard class, please.",b1b2b:"One way or return?",b1b2b1:"A one way ticket, please.",b1b2b1b:"That will be £24 please.",x:"x",x:"x",x:"x",x:"x",x:"x",b1b2b2:"A return ticket, please.",b1b2b2b:"That will be £40 please.",x:"x",x:"x",x:"x",x:"x",x:"x",b1b2b3:"",b1b2b3b:"",x:"x",x:"x",x:"x",b1b3:"Do you have a student discount?",b1b3b:"No, I'm afraid we don't.",b1b3b1:"OK. I'll buy the cheapest ticket you have please.",b1b3b1b:"That will be £24 please.",x:"x",x:"x",x:"x",x:"x",x:"x",b1b3b2:"OK. One standard class ticket please.",b1b3b2b:"That will be £24 please.",x:"x",x:"x",x:"x",x:"x",x:"x",b1b3b3:"",b1b3b3b:"",x:"x",b2:"When is the next train to Liverpool?",b2b:"There is a fast train leaving in 45 minutes, and a slow train in 10 minutes.",b2b1:"How long does each train take?",b2b1b:"The fast train takes 2 hours, the slow one takes over 3 hours.",b2b1b1:"Can I buy a ticket for the slow train then, please.",b2b1b1b:"That will be £24 please.",x:"x",x:"x",x:"x",x:"x",x:"x",b2b1b2:"Can I buy a ticket for the fast train then, please.",b2b1b2b:"That will be £24 please.",x:"x",x:"x",x:"x",x:"x",x:"x",b2b1b3:"How much does each train cost?",b2b1b3b:"They both cost £24 for standard class.",x:"x",x:"x",x:"x",b2b2:"How much does each train cost?",b2b2b:"They both cost £24 for standard class.",b2b2b1:"How much does first class cost?",b2b2b1b:"First class tickets are £40.",x:"x",x:"x",x:"x",x:"x",x:"x",b2b2b2:"Can I buy a ticket for the fast train then, please.",b2b2b2b:"That will be £24 please.",x:"x",x:"x",x:"x",x:"x",x:"x",b2b2b3:"",b2b2b3b:"",x:"x",x:"x",x:"x",b2b3:"Can I buy one ticket for the fast train, please?",b2b3b:"Of course, first class or standard class?",b2b3b1:"First class, please.",b2b3b1b:"That will be £40 please.",x:"x",x:"x",x:"x",x:"x",x:"x",b2b3b2:"Just standard class, please.",b2b3b2b:"That will be £24 please.",x:"x",x:"x",x:"x",x:"x",x:"x",b2b3b3:"",b2b3b3b:"",x:"x",b3:"I have a ticket to Liverpool. What platform should I go to?",b3b:"You should go to Platform 3, there is a train leaving in 10 minutes.",b3b1:"Where is platform 3?",b3b1b:"Downstairs from here, and to your left. There is a big sign.",b3b1b1:"Thank you. Have you ever been to Liverpool?",b3b1b1b:"I have - it's lovely. Have a good journey.",x:"x",x:"x",x:"x",x:"x",x:"x",b3b1b2:"Thank you. And is there a toilet nearby?",b3b1b2b:"It's also downstairs, but to your right. Have a safe trip.",x:"x",x:"x",x:"x",x:"x",x:"x",b3b1b3:"",b3b1b3b:"",x:"x",x:"x",x:"x",b3b2:"Thank you. How long will the train take?",b3b2b:"This is a slow train. It takes about 3 hours.",b3b2b1:"Thank you. Are there any faster trains?",b3b2b1b:"Yes, there is a fast train leaving from platform 8 in about 45 minutes.",x:"x",x:"x",x:"x",x:"x",x:"x",b3b2b2:"That sounds fine. I have a good book with me!",b3b2b2b:"Glad to hear it - have a safe trip!",x:"x",x:"x",x:"x",x:"x",x:"x",b3b2b3:"",b3b2b3b:"",x:"x",x:"x",x:"x",b3b3:"Thank you. How long does it take to walk to platform 3?",b3b3b:"It's about 5 minutes away, so you will need to walk quickly!",b3b3b1:"OK, thank you for your help.",b3b3b1b:"No problem. Have a safe trip!",x:"x",x:"x",x:"x",x:"x",x:"x",b3b3b2:"x",b3b3b2b:"x",x:"x",x:"x",x:"x",x:"x",x:"x",b3b3b3:"x",b3b3b3b:"x"}
var stationDataFrench = {b:"Bienvenue sur train de la Croix de la gare de King. Comment puis-je vous aider?",b1:"Puis-je acheter un billet pour Liverpool s'il vous plaît.",b1b:"Voulez-vous un billet de premi&egravere classe ou Standard?",b1b1:"Premi&egravere classe, s'il vous plaît.",b1b1b:"D'une fa&ccedilon ou retour?",b1b1b1:"Un billet aller simple, s'il vous plaît.",b1b1b1b:"Ce sera £ 24 s'il vous plaît.",x:"x",x:"x",x:"x",x:"x",x:"x",b1b1b2:"Un billet de retour, s'il vous plaît.",b1b1b2b:"Ce sera £ 40 s'il vous plaît.",x:"x",x:"x",x:"x",x:"x",x:"x",b1b1b3:"",b1b1b3b:"",x:"x",x:"x",x:"x",b1b2:"Classe standard, s'il vous plaît.",b1b2b:"D'une fa&ccedilon ou retour?",b1b2b1:"Un billet aller simple, s'il vous plaît.",b1b2b1b:"Ce sera £ 24 s'il vous plaît.",x:"x",x:"x",x:"x",x:"x",x:"x",b1b2b2:"Un billet de retour, s'il vous plaît.",b1b2b2b:"Ce sera £ 40 s'il vous plaît.",x:"x",x:"x",x:"x",x:"x",x:"x",b1b2b3:"",b1b2b3b:"",x:"x",x:"x",x:"x",b1b3:"Avez-vous un rabais &eacutetudiant?",b1b3b:"Non, je crains que nous ne le faisons pas.",b1b3b1:"OK. Je vais acheter le billet le moins cher que vous avez s'il vous plaît.",b1b3b1b:"Ce sera £ 24 s'il vous plaît.",x:"x",x:"x",x:"x",x:"x",x:"x",b1b3b2:"OK. Un billet de classe standard s'il vous plaît.",b1b3b2b:"Ce sera £ 24 s'il vous plaît.",x:"x",x:"x",x:"x",x:"x",x:"x",b1b3b3:"",b1b3b3b:"",x:"x",b2:"Quand est le prochain train pour Liverpool?",b2b:"Il ya un train rapide laissant en 45 minutes, et un train lent en 10 minutes.",b2b1:"Combien de temps chaque train de prendre?",b2b1b:"Le train rapide prend 2 heures, une lente prend plus de 3 heures.",b2b1b1:"Puis-je acheter un billet pour le train lent alors, s'il vous plaît.",b2b1b1b:"Ce sera £ 24 s'il vous plaît.",x:"x",x:"x",x:"x",x:"x",x:"x",b2b1b2:"Puis-je acheter un billet pour le train rapide alors, s'il vous plaît.",b2b1b2b:"Ce sera £ 24 s'il vous plaît.",x:"x",x:"x",x:"x",x:"x",x:"x",b2b1b3:"Combien co&ucircte le co&ucirct de chaque train?",b2b1b3b:"Ils ont tous deux co&ucirctent £ 24 pour la classe standard.",x:"x",x:"x",x:"x",b2b2:"Combien co&ucircte le co&ucirct de chaque train?",b2b2b:"Ils ont tous deux co&ucirctent £ 24 pour la classe standard.",b2b2b1:"Combien co&ucircte de premi&egravere classe?",b2b2b1b:"Billets de premi&egravere classe sont de 40 £.",x:"x",x:"x",x:"x",x:"x",x:"x",b2b2b2:"Puis-je acheter un billet pour le train rapide alors, s'il vous plaît.",b2b2b2b:"Ce sera £ 24 s'il vous plaît.",x:"x",x:"x",x:"x",x:"x",x:"x",b2b2b3:"",b2b2b3b:"",x:"x",x:"x",x:"x",b2b3:"Puis-je acheter un billet pour le train rapide, s'il vous plaît?",b2b3b:"Bien s&ucircr, la premi&egravere classe ou en classe standard?",b2b3b1:"Premi&egravere classe, s'il vous plaît.",b2b3b1b:"Ce sera £ 40 s'il vous plaît.",x:"x",x:"x",x:"x",x:"x",x:"x",b2b3b2:"Juste classe standard, s'il vous plaît.",b2b3b2b:"Ce sera £ 24 s'il vous plaît.",x:"x",x:"x",x:"x",x:"x",x:"x",b2b3b3:"",b2b3b3b:"",x:"x",b3:"J'ai un billet pour Liverpool. Quelle plate-forme dois-je aller?",b3b:"Vous devez aller &agrave la plate-forme 3, il ya un train qui part dans 10 minutes.",b3b1:"O&ugrave est la plate-forme 3?",b3b1b:"En bas d'ici, et &agrave votre gauche. Il est un grand signe.",b3b1b1:"Merci. Avez-vous d&eacutej&agrave &eacutet&eacute &agrave Liverpool?",b3b1b1b:"J'ai - c'est tr&egraves agr&eacuteable. Avoir un bon voyage.",x:"x",x:"x",x:"x",x:"x",x:"x",b3b1b2:"Merci. Et y at-il des toilettes &agrave proximit&eacute?",b3b1b2b:"C'est aussi en bas, mais &agrave votre droite. Bon voyage.",x:"x",x:"x",x:"x",x:"x",x:"x",b3b1b3:"",b3b1b3b:"",x:"x",x:"x",x:"x",b3b2:"Merci. Combien de temps le train aura?",b3b2b:"Il s'agit d'un train lent. Il faut environ 3 heures.",b3b2b1:"Merci. Y at-il des trains plus rapides?",b3b2b1b:"Oui, il ya un train rapide au d&eacutepart de la plate-forme 8 en 45 minutes environ.",x:"x",x:"x",x:"x",x:"x",x:"x",b3b2b2:"Cela sonne bien. J'ai un bon livre avec moi!",b3b2b2b:"Heureux de l'entendre - un voyage s&ucircr!",x:"x",x:"x",x:"x",x:"x",x:"x",b3b2b3:"",b3b2b3b:"",x:"x",x:"x",x:"x",b3b3:"Merci. Combien de temps faut-il pour aller &agrave pied &agrave la plate-forme 3?",b3b3b:"Il est &agrave environ 5 minutes, vous aurez donc besoin de marcher vite!",b3b3b1:"OK, je vous remercie pour votre aide.",b3b3b1b:"Pas de probl&egraveme. Bon voyage!",x:"x",x:"x",x:"x",x:"x",x:"x",b3b3b2:"x",b3b3b2b:"x",x:"x",x:"x",x:"x",x:"x",x:"x",b3b3b3:"x",b3b3b3b:"x"}
var stationDataSpanish = {b:"Bienvenidos a la estaci&oacuten de tren de Kings Cross. &iquestC&oacutemo puedo ayudarle?",b1:"&iquestPuedo comprar un billete para el Liverpool por favor.",b1b:"&iquestTe gustar&iacutea un billete de primera clase o est&aacutendar?",b1b1:"Primera clase, por favor.",b1b1b:"De una forma o de retorno?",b1b1b1:"Un billete de ida, por favor.",b1b1b1b:"Ese ser&aacute £ 24 por favor.",x:"x",x:"x",x:"x",x:"x",x:"x",b1b1b2:"Un billete de vuelta, por favor.",b1b1b2b:"Ese ser&aacute £ 40 por favor.",x:"x",x:"x",x:"x",x:"x",x:"x",b1b1b3:"",b1b1b3b:"",x:"x",x:"x",x:"x",b1b2:"Clase est&aacutendar, por favor.",b1b2b:"De una forma o de retorno?",b1b2b1:"Un billete de ida, por favor.",b1b2b1b:"Ese ser&aacute £ 24 por favor.",x:"x",x:"x",x:"x",x:"x",x:"x",b1b2b2:"Un billete de vuelta, por favor.",b1b2b2b:"Ese ser&aacute £ 40 por favor.",x:"x",x:"x",x:"x",x:"x",x:"x",b1b2b3:"",b1b2b3b:"",x:"x",x:"x",x:"x",b1b3:"&iquestUsted tiene un descuento para estudiantes?",b1b3b:"No, me temo que no lo hacemos.",b1b3b1:"Aceptar. Me voy a comprar el billete m&aacutes barato usted tiene por favor.",b1b3b1b:"Ese ser&aacute £ 24 por favor.",x:"x",x:"x",x:"x",x:"x",x:"x",b1b3b2:"Aceptar. Un boleto de clase est&aacutendar por favor.",b1b3b2b:"Ese ser&aacute £ 24 por favor.",x:"x",x:"x",x:"x",x:"x",x:"x",b1b3b3:"",b1b3b3b:"",x:"x",b2:"&iquestCu&aacutendo es el pr&oacuteximo tren a Liverpool?",b2b:"Hay un tren r&aacutepido dejando en 45 minutos, y un tren lento en 10 minutos.",b2b1:"&iquestCu&aacutento tiempo dura cada tren?",b2b1b:"El tren r&aacutepido tarda 2 horas, el lento tarda m&aacutes de 3 horas.",b2b1b1:"&iquestPuedo comprar un billete para el tren lento entonces, por favor.",b2b1b1b:"Ese ser&aacute £ 24 por favor.",x:"x",x:"x",x:"x",x:"x",x:"x",b2b1b2:"&iquestPuedo comprar un billete para el tren r&aacutepido, entonces, por favor.",b2b1b2b:"Ese ser&aacute £ 24 por favor.",x:"x",x:"x",x:"x",x:"x",x:"x",b2b1b3:"&iquestCu&aacutento cuesta cada tren?",b2b1b3b:"Ambos cuestan £ 24 para la clase est&aacutendar.",x:"x",x:"x",x:"x",b2b2:"&iquestCu&aacutento cuesta cada tren?",b2b2b:"Ambos cuestan £ 24 para la clase est&aacutendar.",b2b2b1:"&iquestCu&aacutento cuesta la primera clase?",b2b2b1b:"Billetes de primera clase son £ 40.",x:"x",x:"x",x:"x",x:"x",x:"x",b2b2b2:"&iquestPuedo comprar un billete para el tren r&aacutepido, entonces, por favor.",b2b2b2b:"Ese ser&aacute £ 24 por favor.",x:"x",x:"x",x:"x",x:"x",x:"x",b2b2b3:"",b2b2b3b:"",x:"x",x:"x",x:"x",B2B3:"&iquestPuedo comprar un billete para el tren r&aacutepido, por favor?",b2b3b:"Por supuesto, en primera clase o clase est&aacutendar?",b2b3b1:"Primera clase, por favor.",b2b3b1b:"Ese ser&aacute £ 40 por favor.",x:"x",x:"x",x:"x",x:"x",x:"x",b2b3b2:"S&oacutelo la clase est&aacutendar, por favor.",b2b3b2b:"Ese ser&aacute £ 24 por favor.",x:"x",x:"x",x:"x",x:"x",x:"x",b2b3b3:"",b2b3b3b:"",x:"x",b3:"Tengo un billete para Liverpool. &iquestQu&eacute plataforma deber&iacutea ir?",b3b:"Hay que ir a la plataforma 3, hay un tren que sale cada 10 minutos.",b3b1:"&iquestD&oacutende est&aacute la plataforma 3?",b3b1b:"En la planta baja de aqu&iacute, y a su izquierda. Hay un gran cartel.",b3b1b1:"Gracias. &iquestAlguna vez has estado en Liverpool?",b3b1b1b:"Tengo - que es precioso. Que tengas un buen viaje.",x:"x",x:"x",x:"x",x:"x",x:"x",b3b1b2:"Gracias. &iquestY hay un inodoro cercano?",b3b1b2b:"Es tambi&eacuten la planta baja, pero a su derecha. Que tengas buen viaje.",x:"x",x:"x",x:"x",x:"x",x:"x",b3b1b3:"",b3b1b3b:"",x:"x",x:"x",x:"x",b3b2:"Gracias. &iquestCu&aacutento tiempo durar&aacute el tren tomar?",b3b2b:"Se trata de un tren lento. Se tarda alrededor de 3 horas.",b3b2b1:"Gracias. &iquestHay trenes m&aacutes r&aacutepidos?",b3b2b1b:"S&iacute, hay un tren r&aacutepido que sale de la plataforma 8 en unos 45 minutos.",x:"x",x:"x",x:"x",x:"x",x:"x",b3b2b2:"Eso suena bien. Tengo un buen libro conmigo!",b3b2b2b:"Me alegra o&iacuter eso - tener un viaje seguro!",x:"x",x:"x",x:"x",x:"x",x:"x",b3b2b3:"",b3b2b3b:"",x:"x",x:"x",x:"x",b3b3:"Gracias. &iquestCu&aacutento tiempo se tarda en caminar hacia la plataforma de 3?",b3b3b:"Est&aacute a unos 5 minutos de distancia, por lo que tendr&aacute que caminar r&aacutepidamente!",b3b3b1:"Bien, gracias por su ayuda.",b3b3b1b:"No hay problema. &iexclBuen viaje!",x:"x",x:"x",x:"x",x:"x",x:"x",b3b3b2:"x",b3b3b2b:"x",x:"x",x:"x",x:"x",x:"x",x:"x",b3b3b3:"x",b3b3b3b:"x"}
var stationDataGerman = {b:"Willkommen in Kreuz Bahnhof K&oumlnigs. Wie kann ich Ihnen helfen?",b1:"Kann ich ein Ticket nach Liverpool bitte.",b1b:"M&oumlchten Sie ein Erste-Klasse-Ticket oder Standard?",b1b1:"Erste Klasse, bitte.",b1b1b:"So oder R&uumlckkehr?",b1b1b1:"Eine einfache Fahrt, bitte.",b1b1b1b:"Das wird £ 24 bitte.",x:"x",x:"x",x:"x",x:"x",x:"x",b1b1b2:"Ein R&uumlckflugticket, bitte.",b1b1b2b:"Das wird £ 40 bitte.",x:"x",x:"x",x:"x",x:"x",x:"x",b1b1b3:"",b1b1b3b:"",x:"x",x:"x",x:"x",b1b2:"Standardklasse, bitte.",b1b2b:"So oder R&uumlckkehr?",b1b2b1:"Eine einfache Fahrt, bitte.",b1b2b1b:"Das wird £ 24 bitte.",x:"x",x:"x",x:"x",x:"x",x:"x",b1b2b2:"Ein R&uumlckflugticket, bitte.",b1b2b2b:"Das wird £ 40 bitte.",x:"x",x:"x",x:"x",x:"x",x:"x",b1b2b3:"",b1b2b3b:"",x:"x",x:"x",x:"x",b1b3:"Haben Sie einen Studentenrabatt?",b1b3b:"Nein, ich f&uumlrchte, wir nicht.",b1b3b1:"OK. Ich werde die g&uumlnstigsten Ticket Sie bitte kaufen.",b1b3b1b:"Das wird £ 24 bitte.",x:"x",x:"x",x:"x",x:"x",x:"x",b1b3b2:"OK. Ein Standard-Klasse-Ticket bitte.",b1b3b2b:"Das wird £ 24 bitte.",x:"x",x:"x",x:"x",x:"x",x:"x",b1b3b3:"",b1b3b3b:"",x:"x",b2:"Wann ist der n&aumlchste Zug nach Liverpool?",b2b:"Es ist ein schneller Zug, der in 45 Minuten, und ein langsamer Zug in 10 Minuten.",b2b1:"Wie lange dauert jeder Zug nehmen?",b2b1b:"Der Schnellzug dauert 2 Stunden, die langsame ein &uumlber 3 Stunden dauert.",b2b1b1:"Kann ich ein Ticket f&uumlr den Bummelzug dann, bitte.",b2b1b1b:"Das wird £ 24 bitte.",x:"x",x:"x",x:"x",x:"x",x:"x",b2b1b2:"Kann ich ein Ticket f&uumlr den Schnellzug dann, bitte.",b2b1b2b:"Das wird £ 24 bitte.",x:"x",x:"x",x:"x",x:"x",x:"x",b2b1b3:"Wie viel kostet jeden Zug kosten?",b2b1b3b:"Beide kosten £ 24 f&uumlr Standard-Klasse.",x:"x",x:"x",x:"x",b2b2:"Wie viel kostet jeden Zug kosten?",b2b2b:"Beide kosten £ 24 f&uumlr Standard-Klasse.",b2b2b1:"Wie viel kostet der ersten Klasse kosten?",b2b2b1b:"Erste-Klasse-Tickets sind 40 £.",x:"x",x:"x",x:"x",x:"x",x:"x",b2b2b2:"Kann ich ein Ticket f&uumlr den Schnellzug dann, bitte.",b2b2b2b:"Das wird £ 24 bitte.",x:"x",x:"x",x:"x",x:"x",x:"x",b2b2b3:"",b2b2b3b:"",x:"x",x:"x",x:"x",b2b3:"Kann ich ein Ticket f&uumlr den Schnellzug, bitte?",b2b3b:"Nat&uumlrlich der ersten Klasse oder Standardklasse?",b2b3b1:"Erste Klasse, bitte.",b2b3b1b:"Das wird £ 40 bitte.",x:"x",x:"x",x:"x",x:"x",x:"x",b2b3b2:"Nur Standard-Klasse, bitte.",b2b3b2b:"Das wird £ 24 bitte.",x:"x",x:"x",x:"x",x:"x",x:"x",b2b3b3:"",b2b3b3b:"",x:"x",b3:"Ich habe ein Ticket f&uumlr Liverpool. Welche Plattform sollte ich gehen?",b3b:"Sie sollten Platform 3 zu gehen, gibt es einen Zug, der in 10 Minuten.",b3b1:"Wo ist Plattform 3?",b3b1b:"Unten von hier, und auf der linken Seite. Es ist ein großes Zeichen.",b3b1b1:"Danke. Haben Sie schon einmal nach Liverpool gewesen?",b3b1b1b:"Ich habe - es ist sehr sch&oumln. Haben Sie eine gute Reise.",x:"x",x:"x",x:"x",x:"x",x:"x",b3b1b2:"Danke. Und gibt es eine Toilette in der N&aumlhe?",b3b1b2b:"Es ist auch die Treppe hinunter, aber auf der rechten Seite. Haben Sie eine sichere Reise.",x:"x",x:"x",x:"x",x:"x",x:"x",b3b1b3:"",b3b1b3b:"",x:"x",x:"x",x:"x",b3b2:"Danke. Wie lange wird die Bahn?",b3b2b:"Dies ist ein langsamer Zug. Es dauert etwa 3 Stunden.",b3b2b1:"Danke. Gibt es schnellere Z&uumlge?",b3b2b1b:"Ja, es ist ein schneller Zug, der von Gleis 8 in etwa 45 Minuten.",x:"x",x:"x",x:"x",x:"x",x:"x",b3b2b2:"Das klingt gut. Ich habe ein gutes Buch mit mir!",b3b2b2b:"Freut mich zu h&oumlren - haben eine gute Fahrt!",x:"x",x:"x",x:"x",x:"x",x:"x",b3b2b3:"",b3b2b3b:"",x:"x",x:"x",x:"x",b3b3:"Danke. Wie lange dauert es, bis zu Plattform 3 gehen?",b3b3b:"Es ist ca. 5 Minuten entfernt, so dass Sie brauchen, um schnell zu Fuß!",b3b3b1:"OK, ich danke Ihnen f&uumlr Ihre Hilfe.",b3b3b1b:"Kein Problem. Wir w&uumlnschen eine gute Reise!",x:"x",x:"x",x:"x",x:"x",x:"x",b3b3b2:"x",b3b3b2b:"x",x:"x",x:"x",x:"x",x:"x",x:"x",b3b3b3:"x",b3b3b3b:"x"}