var conversationData = {
	b: "Welcome to Fat Frank's Fish and Chips! Would you like a table?",
		b1: "Yes, I'd like a table for 2 please.",
			b1b: "Great, please come this way.<br>Would you like some drinks?",
				b1b1: "Yes please. We would like a bottle of red wine.",
					b1b1b: "Of course. Would you like to see the wine menu?",
						b1b1b1: "No thank you. We will just have the 'house' red.",
							b1b1b1b: "Very well. Let me just go and get you some glasses.",
						b1b1b2: "Yes please.",
							b1b1b2b: "OK - I will just bring you the menu.",
						b1b1b3: "No thank you. Just bring us a wine you recommend.",
							b1b1b3b: "I can recommend the Chardonnay, I'll go and fetch a bottle.",
				b1b2: "Yes please. Could we see the menu?",
					b1b2b: "Certainly, here you go. What can I get you?",
						b1b2b1: "Can we have two cans of Coke please.",
							b1b2b1b: "Of course, two Cokes. I'll also bring you a food menu.",
						b1b2b2: "We will have a glass of orange juice and a bottle of beer please.",
							b1b2b2b: "An orange juice and a beer. I'll bring those now, and also a food menu.",
						b1b2b3: "A bottle of white wine, please.",
							b1b2b3b: "Good choice - the house wine is lovely.",
				b1b3: "No thank you. We'll just be having food.",
					b1b3b: "OK. Here is the food menu.",
						b1b3b1: "Thank you. We will have fish and chips please.",
							b1b3b1b: "Two plates of fish and chips - good choice.",
						b1b3b2: "Thank you. We'd like tuna salad and a bowl of chips please.",
							b1b3b2b: "I'm afraid we are out of chips. I will bring you some potatoes instead.",
						b1b3b3: "Thank you. I would like a tuna pizza please.",
							b1b3b3b: "A personal favourite. Coming right up.",
		b2: "No, can I make a reservation for later?",
			b2b: "Of course. What time would like to reserve a table for?",
				b2b1: "Half past eight this evening, please.",
					b2b1b: "That is fine. Would you like a table near the jazz band?",
						b2b1b1: "Yes please.",
							b2b1b1b: "I'll try and get you a table right at the front.",
						b2b1b2: "No thank you.",
							b2b1b2b: "OK, we have a nice table near to the window, which I'll reserve.",
						b2b1b3: "I don't mind.",
							b2b1b3b: "Very well then. See you later!",
				b2b2: "What time are you open until?",
					b2b2b: "We are open until 10pm tonight.",
						b2b2b1: "OK - please can we book a table at 9pm.",
							b2b2b1b: "Yes sure, a table at 9pm.",
						b2b2b2: "Great, can I book a table for 4 people at 8 o'clock please?",
							b2b2b2b: "Certainly. A table for 4, at 8 o'clock.",
						b2b2b3: "Sorry, actually, that's too early for me.",
							b2b2b3b: "I'm sorry to hear that. Maybe another day then.",
				b2b3: "I would like to reserve a table for tomorrow lunch.",
					b2b3b: "OK - how many people will be eating?",
						b2b3b1: "Just me, thank you.",
							b2b3b1b: "Very well. A table for one, tomorrow at lunch.",
						b2b3b2: "It will be myself and my brother.",
							b2b3b2b: "Good, a table for two at lunchtime tomorrow.",
						b2b3b3: "We'll have a table for four people please.",
							b2b3b3b: "Let me just check... yes, that's fine. See you tomorrow.",
		b3: "No, I'd like to order a take-away please.",
			b3b: "OK, here is the take-away menu.",
				b3b1: "I'll have a burger and a beer please.",
					b3b1b: "I'm afraid we're out of beers - can I get you anything else instead?",
						b3b1b1: "I'll have a Coke instead.",
							b3b1b1b: "Fantastic choice. I'll bring you your burger and Coke shortly.",
						b3b1b2: "Do you have any other alcoholic drinks?",
							b3b1b2b: "We do have shots. I'll bring you a shot with your burger.",
						b3b1b3: "No thanks - I'm off.",
							b3b1b3b: "Oh, OK. Come back again soon - we normally have a good range of beer. Stella and Fosters mainly.",
				b3b2: "This menu looks awful! Do you have anything nicer?",
					b3b2b: "I'm afraid this is all we have, sir.",
						b3b2b1: "OK - I'll get one small 'Fish Surprise' please.",
							b3b2b1b: "Coming right up. It really is quite a surprising dish.",
						b3b2b2: "Sorry - I am leaving.",
							b3b2b2b: "Suit yourself. Come back again soon!",
						b3b2b3: "I'll just have a water please.",
							b3b2b3b: "I'm afraid we're having problems with our drainage, so that won't be possible, sir.",
				b3b3: "Can you recommend anything?",
					b3b3b: "The eels are very tasty, and the soup goes well with them.",
						b3b3b1: "Great, I'll get the eels and the soup then please.",
							b3b3b1b: "A good choice - eels with leek soup to take away.",
						b3b3b2: "I don't like eels - what else do you have?",
							b3b3b2b: "We have a wide variety of tuna products.",
						b3b3b3: "I think I'll get the soup and a tuna pizza please.",
							b3b3b3b: "Excellent choice - the tuna pizza is a personal favourite.",

}